test000.c:4: エラー: `__func__' が函数の外側で参照されています.
test000.c:4: エラー: `a' に対する初期化指定子が不正です.
