test003.c: 函数 `f' :
test003.c:8: エラー: `a' は宣言されていません.
test003.c:8: エラー: `b' は宣言されていません.
