test126.c: 函数 `main' :
test126.c:5: エラー: `p' に対する代入演算子が不正です.
