test010.c:6: エラー: `a' は宣言されていません.
test010.c:8: エラー: `a' は宣言されていません.
test010.c: 函数 `main' :
test010.c:12: エラー: 函数ではない `f' を呼び出しました.
test010.c:13: エラー: 函数ではない `g' を呼び出しました.
test010.c:17: エラー: `a' は宣言されていません.
test010.c:17: エラー: `f' が再宣言されています.
test010.c:6: エラー: ここで宣言されていました.
test010.c:18: error: syntax error before `int' token.
