a.obj : error LNK2019: 未解決の外部シンボル a が関数 _test_main で参照されました。 [D:\home\khasegawa\lang\40_test_tool\vs_wrapper2\vs_wrapper2.vcxproj]
D:\home\khasegawa\lang\40_test_tool\vs_wrapper2\x64\Debug\vs_wrapper2.exe : fatal error LNK1120: 1 件の未解決の外部参照 [D:\home\khasegawa\lang\40_test_tool\vs_wrapper2\vs_wrapper2.vcxproj]
  a.obj : error LNK2019: 未解決の外部シンボル a が関数 _test_main で参照されました。 [D:\home\khasegawa\lang\40_test_tool\vs_wrapper2\vs_wrapper2.vcxproj]
  D:\home\khasegawa\lang\40_test_tool\vs_wrapper2\x64\Debug\vs_wrapper2.exe : fatal error LNK1120: 1 件の未解決の外部参照 [D:\home\khasegawa\lang\40_test_tool\vs_wrapper2\vs_wrapper2.vcxproj]
