test002.c:6: エラー: `__func__' が函数の外側で参照されています.
test002.c: 函数 `f' :
test002.c:10: エラー: `q' に対する初期化指定子が不正です. 修飾子が失われます.
test002.c:11: エラー: `pa' に対する初期化指定子が不正です.
test002.c:12: エラー: 予約識別子 `__func__' が宣言されています.
