test003.c: 函数 `f' :
test003.c:6: エラー: `a' は宣言されていません.
test003.c:7: エラー: `b' は宣言されていません.
test003.c: 函数 `g' :
test003.c:14: エラー: `c' は宣言されていません.
test003.c:15: エラー: `d' は宣言されていません.
