test003.c: 函数 `f' :
test003.c:7: エラー: `a' が int[] として宣言されています.
test003.c:8: エラー: `b' が int[] として宣言されています.
test003.c:9: エラー: `c' が int[] として宣言されています.
