test002.c:4: エラー: `f' は宣言されていません.
test002.c:4: エラー: 函数ではない `f' を呼び出しました.
